Setup of our environment

In [1]:
#import ROOT

#Color printing
from termcolor import colored

#General data operations library
import math
import numpy as np

#HEP specific tools
import scipy.constants as scipy_constants

#Plotting libraries
import matplotlib.pyplot as plt

#Increase plots font size
params = {'legend.fontsize': 'xx-large',
          'figure.figsize': (10, 7),
         'axes.labelsize': 'xx-large',
         'axes.titlesize':'xx-large',
         'xtick.labelsize':'xx-large',
         'ytick.labelsize':'xx-large'}
plt.rcParams.update(params)

In [2]:
G_F = scipy_constants.physical_constants["Fermi coupling constant"]
m_e = scipy_constants.physical_constants["electron mass energy equivalent in MeV"]
m_mu = scipy_constants.physical_constants["muon mass energy equivalent in MeV"]

print("Fermi constant: {} +- {} {}".format(G_F[0], G_F[2], G_F[1]))
print("muon mass: \t{} +- {} {}".format(m_mu[0], m_mu[2], m_mu[1]))
print("electron mass: \t{} +- {} {}".format(m_e[0], m_e[2], m_e[1]))

G_F = G_F[0]
m_e = m_e[0]
m_mu = m_mu[0]

Fermi constant: 1.1663787e-05 +- 6e-12 GeV^-2
muon mass: 	105.6583755 +- 2.3e-06 MeV
electron mass: 	0.51099895 +- 1.5e-10 MeV


## Our homework functions

In [18]:
minS = 50
maxS = 200

m_Z = 92.1876
gamma_Z = 2.4952

def BreitWigner(s, m, gamma):
    gamma_small = np.sqrt(m ** 2 * (m ** 2 + gamma ** 2))
    k = (2 * np.sqrt(2) * m * gamma * gamma_small) / (np.pi * np.sqrt(m ** 2 + gamma_small))
    
    distr = k / ((s ** 2 - m ** 2) ** 2 + m ** 2 * gamma ** 2)
    return distr

def generateCandidateEnergy(nPoints):
    gamma = gamma_Z
    s = (maxS-minS)*np.random.random(nPoints) + minS
    print(s)
    x = np.random.random_sample(nPoints)
    bw_values = BreitWigner(s, m_Z, gamma)  # it is equivalent to p
    bw_values = bw_values / np.max(bw_values)
    accepted = x < bw_values
    return s[accepted]/2.0

def generateCandidateMomenta(energy):
    howmany = len(energy)
    
    c = np.random.random_sample([howmany, 3]) 
    csum = np.sum(c, axis=1)  # we need to generate shoots so that their sum equals energy
    cdiv = np.asanyarray(1 / csum)  # vector we multiply our matrix
    cdivT = np.vstack(cdiv)  # transposed vector

    result = np.multiply(c, cdivt)  # matrix multiplied  by sum
    energyT = np.vstack(energy)  # transposed vector of energies
    
    p = np.multiply(result, energyT)
       
    p4_electron = np.column_stack([energy, px,py,pz])
    p4_positron = np.column_stack([energy, -px,-py,-pz])
    return  p4_electron, p4_positron

def generateEvents(nPoints):
    energy = generateCandidateEnergy(nPoints)
    data = generateCandidateMomenta(energy)
    return data

def invMass(p4):
    metric = np.array([1,-1,-1,-1])
    p4_square = p4*(metric*p4)
    m = np.sqrt(np.sum(p4_square, axis=1))
    return m

## I have done here multiplication of two arrays; each row is multiplied by different value; thanks to this now we can generate N rows (for each energies) consisting of 3 momentum values


In [13]:
energy = np.array([1,2,3,4,5])
howmany = 5

c = np.random.random_sample([howmany, 3]) 
csum = np.sum(c, axis=1)  # we need to generate shoots so that their sum equals energy
cdiv = np.asanyarray(1 / csum)  # vector we multiply our matrix
cdivT = np.vstack(cdiv)  # transposed vector

result = np.multiply(c, cdivT)  # matrix multiplied  by sum
energyT = np.vstack(energy)  # transposed vector of energies

p = np.multiply(result, energyT)

a = np.array([[1, 1, 1, 1], [2, 2, 2, 2]])
b = np.array([[2, 2, 2 ,2], [2, 2, 2 ,2]])



d = np.column_stack((a))

print(d)
# hellos a

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [12]:
c = np.random.random_sample([5, 3]) 

csum = np.sum(c, axis=1)
print("\nMatrix c : \n", c)
print(csum)

cdiv = np.asanyarray(1 / csum)
cdivt = np.vstack(cdiv)
print(cdivt)

r = np.multiply(c, cdivt)



Matrix c : 
 [[0.81484557 0.85434373 0.54981559]
 [0.1485336  0.54395243 0.28816729]
 [0.90288503 0.79645387 0.70334006]
 [0.20726179 0.91955511 0.48138065]
 [0.34183066 0.04446276 0.55696528]]
[2.21900489 0.98065332 2.40267895 1.60819756 0.94325871]
[[0.45065245]
 [1.01972836]
 [0.41620209]
 [0.62181415]
 [1.06015453]]


## Here are energies generated

In [19]:
nPoints = 50000

e_min = 50
e_max = 200

energies = generateCandidateEnergy(nPoints)
print("Number of accepted events:\t",energies.shape[0])
print("Accepted events fraction:\t",energies.shape[0]/nPoints)

energies 


[171.66544597  70.78698855 113.73236239 ... 196.88646282  56.24100139
 188.6108908 ]
Number of accepted events:	 1337
Accepted events fraction:	 0.02674


array([46.75420986, 47.32219011, 46.37736778, ..., 44.90097663,
       45.20673949, 39.89031136])

## Here is working generating momenta


In [ ]:
b = generateCandidateMomenta(energies)
b

## First test plots

In [ ]:
%%time

nPoints = 1000000
p4_electron, p4_positron = generateEvents(nPoints)
m = invMass(p4_electron + p4_positron)
#print("Generated {} events for {} tries. \nEfficiency: {:3.2f}".format(m.shape[0], nPoints, float(m.shape[0])/nPoints))

#fig, axes = plt.subplots(2,2, figsize=(12, 12))
#axes[0,0].plot(m, BreitWigner(m, m_Z, gamma_Z), "o",label="Breit-wigner");
#axes[0,0].hist(..., label=r"$e^{+}e^{-}$ MC data");
#axes[0,0].set_xlabel(r"invariant mass [GeV/$c^{2}$]")
#axes[0,0].set_ylabel("probability density")
#axes[0,0].legend(loc="upper right");